# Generated by Django 4.1.7 on 2023-05-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caracteristica_propiedad_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambientes', models.CharField(choices=[('Monoambiente', 'Monoambiente'), ('2 Ambientes', '2 Ambientes'), ('3 Ambientes', '3 Ambientes'), ('4 Ambientes', '4 Ambientes'), ('5 Ambientes', '5 Ambientes')], default='Monoambiente', max_length=50, null=True)),
                ('baños', models.IntegerField(null=True)),
                ('dormitorios', models.IntegerField(null=True)),
                ('cocina', models.IntegerField(null=True)),
                ('living', models.IntegerField(null=True)),
                ('comedor', models.IntegerField(null=True)),
                ('garage', models.IntegerField(null=True)),
                ('sotano', models.IntegerField(null=True)),
                ('terrasa', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='datos_propiedad_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Terreno', 'terreno'), ('Local comercial', 'Local comercial'), ('PH', 'ph'), ('Quinta vacacacional', 'Quinta vacacional'), ('Oficina comercial', 'Oficina comercial'), ('Garage', 'Garage'), ('Bodega-Galpon', 'Bodega-Galpon'), ('Fondo de comercio', 'Fondo de comercio'), ('Hotel', 'Hotel'), ('Deposito', 'Deposito'), ('Bodega, niho o parcela', 'Bodega, niho o parcela'), ('Consultorio', 'Consultorio')], default='Casa', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('parcela', models.IntegerField(null=True)),
                ('lote', models.CharField(max_length=50, null=True)),
                ('tamaño', models.CharField(max_length=50, null=True)),
                ('metros2', models.CharField(max_length=50, null=True)),
                ('clave_c', models.CharField(max_length=50, null=True)),
                ('titular', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dueño_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueño', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
