# Generated by Django 4.1.7 on 2023-05-01 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_propiedad_model',
            name='dueño',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bd_app.dueño_model'),
            preserve_default=False,
        ),
    ]
