# Generated by Django 4.1.7 on 2023-05-01 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0002_datos_propiedad_model_dueño'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica_propiedad_model',
            name='propiedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bd_app.datos_propiedad_model'),
            preserve_default=False,
        ),
    ]
